import torch
import torch.nn as nn
import torch.nn.functional as F
from onnxruntime.quantization import QuantType, quantize_dynamic


def map_labels_to_tensor(target_probs: dict, active_users: list, context_subgroup: str) -> torch.Tensor:
    """
    Maps variable string labels from the JSON corpus to the fixed 10-dimensional output tensor.
    Indices 0-6: Top 7 Active Users, Index 7: Other/Unknown, Index 8: Subgroup, Index 9: Global.
    """
    tensor = torch.zeros(10)
    for key, prob in target_probs.items():
        if key == "global":
            tensor[9] += prob
        elif key == context_subgroup:
            tensor[8] += prob
        elif key in active_users and active_users.index(key) < 7:
            tensor[active_users.index(key)] += prob
        else:
            # Map low-frequency or unknown users to the 'Other' index (7)
            tensor[7] += prob

    # Normalize to ensure sum is 1.0 in case of rounding errors
    return tensor / (tensor.sum() + 1e-8)


class LobsterTalkStudent(nn.Module):
    def __init__(self, input_dim=64, num_classes=10):
        super().__init__()
        # O(1) Feedforward architecture as per Section 3
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 16)
        self.fc3 = nn.Linear(16, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        # Note: Softmax is omitted here; applied natively during loss/inference
        return self.fc3(x)


def distillation_loss(student_logits, teacher_probs):
    """
    Computes KL-Divergence between Student and Teacher.
    Assumes teacher_probs are already valid probabilities generated by the LLM.
    """
    student_log_probs = F.log_softmax(student_logits, dim=1)
    # PyTorch KLDivLoss expects input in log-space and target in linear-space
    loss = F.kl_div(student_log_probs, teacher_probs, reduction="batchmean")
    return loss


def export_and_quantize(model: nn.Module, filepath: str = "lobstertalk_fp32.onnx") -> None:
    """
    Traces the PyTorch model, exports to FP32 ONNX, and applies dynamic INT8 quantization.
    """
    # ONNX export + ORT quantization should run on CPU.
    # If training happened on CUDA, exporting a CUDA-resident module can trigger
    # torch.export/onnx dynamo FakeTensor device propagation errors.
    # Export a CPU copy deterministically.
    model.eval()

    orig_device: torch.device | None = None
    try:
        orig_device = next(model.parameters()).device
    except StopIteration:
        orig_device = torch.device("cpu")

    model.to("cpu")

    # Dummy input must not require gradients during eval/export
    dummy_input = torch.randn(1, 64, requires_grad=False, device="cpu")

    # 1. Export standard FP32 ONNX graph
    torch.onnx.export(
        model,
        (dummy_input,),
        filepath,
        export_params=True,
        opset_version=18,
        do_constant_folding=False,
        input_names=["input_X"],
        output_names=["output_logits"],
        # Force legacy exporter path for maximum compatibility.
        # Newer torch versions may default to `torch.export` (dynamo) which can
        # fail in mixed device environments.
        dynamo=False,
    )

    # 2. Apply Dynamic INT8 Quantization for OpenClaw distribution
    quantized_filepath = (
        filepath.replace("_fp32.onnx", "_int8.onnx")
        if "_fp32.onnx" in filepath
        else filepath.replace(".onnx", "_int8.onnx")
    )
    quantize_dynamic(
        model_input=filepath,
        model_output=quantized_filepath,
        weight_type=QuantType.QUInt8,
    )
    print(f"Successfully exported quantized student model to {quantized_filepath}")

    # Restore model device for caller.
    if orig_device is not None:
        model.to(orig_device)

