#!/usr/bin/env node
/**
 * Compose dist/_headers = public/_headers + generated rules.
 *
 * WHY THE .md ENDPOINTS NEED THIS
 *
 * src/pages/docs/[slug].md.ts returns `Content-Type: text/plain; charset=utf-8`
 * and says in its own comment why: text/markdown makes browsers download the
 * file, so the "View this page as Markdown" link reads as broken to a human who
 * clicks it. Under `output: "static"` that Response header is DISCARDED - Astro
 * keeps the body and writes dist/docs/<slug>.md, and Cloudflare then types the
 * file from its extension. The intent was written down and then silently lost
 * at build time.
 *
 * Cloudflare's _headers overrides what it would ordinarily send for static
 * assets, which is exactly the hook needed. (The documented caveat that
 * _headers does not apply to Pages Functions responses is irrelevant here: this
 * is an assets-only Worker with no script at all - see wrangler.jsonc.)
 *
 * WHY GENERATED, NOT A GLOB
 *
 * `/docs/*` in _headers would match the 17 rendered HTML doc pages too and
 * serve the entire protocol reference as source code. Cloudflare's matching
 * does not give a "only this extension" form that can be relied on here, so
 * each file gets a literal rule. 17 of the documented 100-rule budget.
 *
 * Enumerated from dist/ rather than imported from src/docs-allowlist.ts on
 * purpose: this describes what was actually built. A doc that failed to emit
 * cannot get a rule pointing at nothing, and this stays a plain .mjs with no
 * TypeScript loader.
 *
 * Rewriting dist/_headers from public/_headers each run (rather than appending)
 * keeps it idempotent - two builds in a row cannot double up.
 *
 * Usage: runs automatically as the last step of `bun run build`.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "public", "_headers");
const DIST = join(ROOT, "dist");
const OUT = join(DIST, "_headers");

if (!existsSync(DIST)) {
  console.error("dist/ missing - run `astro build` first");
  process.exit(1);
}

const SITE = process.env.SITE_URL ?? "https://clawbits.ai";

const slugs = readdirSync(join(DIST, "docs"))
  .filter((f) => f.endsWith(".md"))
  .map((f) => f.slice(0, -".md".length))
  .sort();

if (slugs.length === 0) {
  console.error("no dist/docs/*.md files found - did the .md endpoint stop emitting?");
  process.exit(1);
}

// Cloudflare documents a 100-rule limit. public/_headers uses a handful; fail
// loudly rather than let rules be silently dropped once the corpus grows.
// A "rule" is a path pattern: a line starting in column 0 that is not a comment
// and not blank. Header lines are indented and do not count.
const HAND_WRITTEN_RULES = readFileSync(SOURCE, "utf8")
  .split("\n")
  .filter((l) => l.trim() !== "" && !l.startsWith("#") && !/^\s/.test(l)).length;
if (HAND_WRITTEN_RULES + slugs.length > 100) {
  console.error(
    `_headers would define ${HAND_WRITTEN_RULES + slugs.length} rules; Cloudflare's limit is 100.`,
  );
  process.exit(1);
}

const generated = [
  "",
  "# ─────────────────────────────────────────────────────────────────────────",
  "# GENERATED by scripts/build-headers.mjs - edit that file, not this one.",
  "#",
  "# One rule per raw-Markdown doc endpoint:",
  "#",
  "#   Content-Type  text/plain so browsers RENDER these instead of downloading",
  "#                 them. The route handler sets this too, but `output: static`",
  "#                 throws its headers away, so this is the only copy that",
  "#                 survives to production.",
  "#   Link          marks the rendered page as canonical. Both URLs carry the",
  "#                 same text, and llms.txt now points crawlers at the .md; the",
  "#                 canonical keeps that from reading as duplicate content and",
  "#                 concentrates ranking on the page a human should land on.",
  "#                 X-Robots-Tag: noindex would ALSO solve the duplication, and",
  "#                 is wrong here - it would hide these files from the AI",
  "#                 crawlers robots.txt exists to invite.",
  "# ─────────────────────────────────────────────────────────────────────────",
  "",
  ...slugs.flatMap((slug) => [
    `/docs/${slug}.md`,
    "  Content-Type: text/plain; charset=utf-8",
    `  Link: <${new URL(`/docs/${slug}/`, SITE).href}>; rel="canonical"`,
    "",
  ]),
].join("\n");

writeFileSync(OUT, readFileSync(SOURCE, "utf8").trimEnd() + "\n" + generated);

console.log(
  `build-headers - ${slugs.length} Markdown endpoints typed text/plain ` +
    `(${HAND_WRITTEN_RULES + slugs.length}/100 rules), canonical -> ${SITE}`,
);
