// Auto-generated from clawbits/datastructures/known_answers.py — do not edit by hand.
export const BUNDLED_KNOWN_ANSWERS: Readonly<Record<string, string>> = Object.freeze({
  "What is the capital of France?": "PARIS",
  "What animal is known as the king of the jungle?": "LION",
  "What color do you get when you mix red and blue?": "PURPLE",
  "What is the largest planet in our solar system?": "JUPITER",
  "What is the chemical symbol for water?": "H2O",
  "What is the opposite of hot?": "COLD",
  "What do bees produce?": "HONEY",
  "What is the fastest land animal?": "CHEETAH",
  "What is the largest ocean on Earth?": "PACIFIC",
  "What do you call a baby cat?": "KITTEN",
  "What is the capital of England?": "LONDON",
  "What fruit is known for keeping doctors away?": "APPLE",
  "What gas do plants absorb from the atmosphere?": "CARBON",
  "What is the hardest natural substance?": "DIAMOND",
  "What is the smallest prime number?": "TWO",
  "What instrument measures earthquakes?": "SEISMOMETER",
  "What is the currency of Japan?": "YEN",
  "What organ in the human body produces insulin?": "PANCREAS",
  "What is the study of stars called?": "ASTRONOMY",
  "What metal is liquid at room temperature?": "MERCURY",
  "What is the largest mammal in the world?": "WHALE",
  "What do you call a group of lions?": "PRIDE",
  "What is the opposite of north?": "SOUTH",
  "What is the main ingredient in bread?": "FLOUR",
  "What season comes after winter?": "SPRING",
  "What is the capital of Italy?": "ROME",
  "What do you call frozen rain?": "HAIL",
  "What bird is known for its colorful tail feathers?": "PEACOCK",
  "What is the largest desert in the world?": "SAHARA",
  "What do you call a baby sheep?": "LAMB",
  "What is the opposite of light?": "DARK",
  "What metal is used to make cans?": "ALUMINUM",
  "What is the capital of Spain?": "MADRID",
  "What do spiders spin?": "WEBS",
  "What is the smallest country in the world?": "VATICAN",
  "What is the main gas in the air we breathe?": "NITROGEN",
  "What do you call a baby horse?": "FOAL",
  "What is the opposite of up?": "DOWN",
  "What tree produces acorns?": "OAK",
  "What is the capital of Germany?": "BERLIN",
  "What do you call a group of fish?": "SCHOOL",
  "What is the tallest mountain in the world?": "EVEREST",
  "What planet is known as the Red Planet?": "MARS",
  "What do you call a baby cow?": "CALF",
  "What is the opposite of big?": "SMALL",
  "What is the capital of Russia?": "MOSCOW",
  "What do you call a baby dog?": "PUPPY",
  "What is the largest bird that cannot fly?": "OSTRICH",
  "What is the main ingredient in glass?": "SAND",
  "What do you call a baby pig?": "PIGLET",
  "What is the opposite of happy?": "SAD",
  "What is the capital of Canada?": "OTTAWA",
  "What do you call a group of geese?": "GAGGLE",
  "What is the smallest bone in the human body?": "STAPES",
  "What gas makes up most of the sun?": "HYDROGEN",
  "What do you call a baby bear?": "CUB",
  "What is the opposite of fast?": "SLOW",
  "What is the capital of Australia?": "CANBERRA",
  "What do you call a group of wolves?": "PACK",
  "What is the largest land animal?": "ELEPHANT",
  "What is the main ingredient in steel?": "IRON",
  "What do you call a baby deer?": "FAWN",
  "What is the opposite of old?": "NEW",
  "What is the capital of China?": "BEIJING",
  "What do you call a group of birds?": "FLOCK",
  "What is the fastest bird in the world?": "FALCON",
  "What is the main ingredient in concrete?": "CEMENT",
  "What do you call a baby rabbit?": "BUNNY",
  "What is the opposite of wet?": "DRY",
  "What is the capital of Brazil?": "BRASILIA",
  "What do you call a group of bees?": "SWARM",
  "What is the largest fish in the ocean?": "WHALE",
  "What is the main ingredient in pencils?": "GRAPHITE",
  "What do you call a baby duck?": "DUCKLING",
  "What is the opposite of soft?": "HARD",
  "What is the capital of India?": "DELHI",
  "What do you call a group of ants?": "COLONY",
  "What is the tallest animal in the world?": "GIRAFFE",
  "What is the main ingredient in soap?": "LYE",
  "What do you call a baby goose?": "GOSLING",
  "What is the opposite of empty?": "FULL",
  "What is the capital of Egypt?": "CAIRO",
  "What do you call a group of dolphins?": "POD",
  "What is the fastest fish in the ocean?": "SAILFISH",
  "What is the main ingredient in butter?": "CREAM",
  "What do you call a baby swan?": "CYGNET",
  "What is the opposite of thin?": "THICK",
  "What is the capital of Mexico?": "MEXICO",
  "What do you call a group of elephants?": "HERD",
  "What is the largest snake in the world?": "ANACONDA",
  "What is the main ingredient in wine?": "GRAPES",
  "What do you call a baby kangaroo?": "JOEY",
  "What is the opposite of loud?": "QUIET",
  "What is the capital of Japan?": "TOKYO",
  "What do you call a group of crows?": "MURDER",
  "What is the largest cat in the world?": "TIGER",
  "What is the main ingredient in chocolate?": "COCOA",
  "What do you call a baby owl?": "OWLET",
  "What is the opposite of clean?": "DIRTY",
  "What is the capital of Argentina?": "BUENOS",
  "What do you call a group of whales?": "POD",
  "What is the fastest insect in the world?": "DRAGONFLY",
  "What is the main ingredient in beer?": "BARLEY",
  "What do you call a baby seal?": "PUP",
  "What is the opposite of near?": "FAR",
  "What is the capital of Turkey?": "ANKARA",
  "What do you call a group of penguins?": "COLONY",
  "What is the largest rodent in the world?": "CAPYBARA",
  "What is the main ingredient in tea?": "LEAVES",
  "What do you call a baby whale?": "CALF",
  "What is the opposite of first?": "LAST",
  "What is the capital of South Korea?": "SEOUL",
  "What do you call a group of sheep?": "FLOCK",
  "What is the largest lizard in the world?": "KOMODO",
  "What is the main ingredient in coffee?": "BEANS",
  "What do you call a baby frog?": "TADPOLE",
  "What is the opposite of high?": "LOW",
  "What is the capital of Thailand?": "BANGKOK",
  "What do you call a group of zebras?": "DAZZLE",
  "What is the largest bird of prey?": "CONDOR",
  "What is the main ingredient in vinegar?": "ACID",
  "What do you call a baby turtle?": "HATCHLING",
  "What is the opposite of young?": "OLD",
  "What is the capital of Netherlands?": "AMSTERDAM",
  "What do you call a group of flamingos?": "FLAMBOYANCE",
  "What is the largest spider in the world?": "TARANTULA",
  "What is the main ingredient in salt?": "SODIUM",
  "What do you call a baby eagle?": "EAGLET",
  "What is the opposite of rich?": "POOR",
  "What is the capital of Sweden?": "STOCKHOLM",
  "What do you call a group of owls?": "PARLIAMENT",
  "What is the largest primate in the world?": "GORILLA",
  "What is the main ingredient in sugar?": "SUCROSE",
  "What do you call a baby penguin?": "CHICK",
  "What is the opposite of strong?": "WEAK",
  "What is the capital of Norway?": "OSLO",
  "What do you call a group of kangaroos?": "MOB",
  "What is the largest amphibian in the world?": "SALAMANDER",
  "What is the main ingredient in milk?": "LACTOSE",
  "What do you call a baby elephant?": "CALF",
  "What is the opposite of heavy?": "LIGHT",
  "What is the capital of Finland?": "HELSINKI",
  "What do you call a group of starfish?": "GALAXY",
  "What is the largest butterfly in the world?": "ATLAS",
  "What is the main ingredient in honey?": "FRUCTOSE",
  "What do you call a baby giraffe?": "CALF",
  "What is the opposite of wide?": "NARROW",
  "What is the capital of Denmark?": "COPENHAGEN",
  "What do you call a group of locusts?": "SWARM",
  "What is the largest beetle in the world?": "HERCULES",
  "What is the main ingredient in cheese?": "CASEIN",
  "What do you call a baby hippo?": "CALF",
  "What is the opposite of rough?": "SMOOTH",
  "What is the capital of Austria?": "VIENNA",
  "What do you call a group of ravens?": "UNKINDNESS",
  "What is the largest freshwater fish?": "STURGEON",
  "What is the main ingredient in bread dough?": "YEAST",
  "What do you call a baby rhino?": "CALF",
  "What is the opposite of sharp?": "DULL",
  "What is the capital of Switzerland?": "BERN",
  "What do you call a group of gorillas?": "BAND",
  "What is the largest marsupial?": "KANGAROO",
  "What is the main ingredient in pasta?": "WHEAT",
  "What do you call a baby crocodile?": "HATCHLING",
  "What is the opposite of bitter?": "SWEET",
  "What is the capital of Belgium?": "BRUSSELS",
  "What do you call a group of baboons?": "TROOP",
  "What is the largest carnivore on land?": "BEAR",
  "What is the main ingredient in ice cream?": "CREAM",
  "What do you call a baby alligator?": "HATCHLING",
  "What is the opposite of sour?": "SWEET",
  "What is the capital of Portugal?": "LISBON",
  "What do you call a group of chimpanzees?": "COMMUNITY",
  "What is the largest herbivore on land?": "ELEPHANT",
  "What is the main ingredient in mayonnaise?": "OIL",
  "What do you call a baby shark?": "PUP",
  "What is the opposite of shallow?": "DEEP",
  "What is the capital of Ireland?": "DUBLIN",
  "What do you call a group of meerkats?": "MOB",
  "What is the largest nocturnal animal?": "ELEPHANT",
  "What is the main ingredient in mustard?": "SEEDS",
  "What do you call a baby octopus?": "LARVAE",
  "What is the opposite of early?": "LATE",
  "What is the capital of Scotland?": "EDINBURGH",
  "What do you call a group of otters?": "RAFT",
  "What is the largest diurnal animal?": "ELEPHANT",
  "What is the main ingredient in ketchup?": "TOMATOES",
  "What do you call a baby squid?": "LARVAE",
  "What is the opposite of smooth?": "ROUGH",
  "What is the capital of Wales?": "CARDIFF",
  "What do you call a group of seals?": "COLONY",
  "What is the largest animal with a shell?": "TURTLE",
  "What is the main ingredient in jam?": "FRUIT",
  "What do you call a baby jellyfish?": "POLYP",
  "What is the opposite of modern?": "ANCIENT",
  "What is the capital of New Zealand?": "WELLINGTON",
  "What do you call a group of tigers?": "STREAK",
  "What is the largest venomous snake?": "COBRA",
  "What is the main ingredient in yogurt?": "BACTERIA",
  "What do you call a baby starfish?": "LARVAE",
  "What is the opposite of simple?": "COMPLEX",
  "What is the capital of South Africa?": "CAPE",
  "What do you call a group of leopards?": "LEAP",
  "What is the largest non-venomous snake?": "PYTHON",
  "What is the main ingredient in pickles?": "VINEGAR",
  "What do you call a baby seahorse?": "FRY",
  "What is the opposite of artificial?": "NATURAL",
  "What is the capital of Chile?": "SANTIAGO",
  "What do you call a group of cheetahs?": "COALITION",
  "What is the largest extinct animal?": "DINOSAUR",
  "What is the main ingredient in salad dressing?": "OIL",
  "What do you call a baby lobster?": "LARVAE",
  "What is the opposite of transparent?": "OPAQUE",
  "What is the capital of Peru?": "LIMA",
  "What do you call a group of jaguars?": "PROWL",
  "What is the largest flying animal today?": "ALBATROSS",
  "What is the main ingredient in cereal?": "GRAINS",
  "What do you call a baby crab?": "LARVAE",
  "What is the opposite of flexible?": "RIGID",
  "What is the capital of Colombia?": "BOGOTA",
  "What do you call a group of panthers?": "PROWL",
  "What is the largest extinct bird?": "MOA",
  "What is the main ingredient in soup?": "BROTH",
  "What do you call a baby shrimp?": "LARVAE",
  "What is the opposite of permanent?": "TEMPORARY",
  "What is the capital of Venezuela?": "CARACAS",
  "What do you call a group of lynx?": "CLUSTER",
  "What is the largest extinct mammal?": "MAMMOTH",
  "What is the main ingredient in stew?": "MEAT",
  "What do you call a baby clam?": "LARVAE",
  "What is the opposite of genuine?": "FAKE",
  "What is the capital of Ecuador?": "QUITO",
  "What do you call a group of pumas?": "PROWL",
  "What is the largest prehistoric fish?": "MEGALODON",
  "What is the main ingredient in curry?": "SPICES",
  "What do you call a baby oyster?": "SPAT",
  "What is the opposite of visible?": "INVISIBLE",
  "What is the capital of Uruguay?": "MONTEVIDEO",
  "What do you call a group of bobcats?": "CLUTTER",
  "What is the largest prehistoric bird?": "ARGENTAVIS",
  "What is the main ingredient in pizza?": "DOUGH",
  "What do you call a baby mussel?": "LARVAE",
  "What is the opposite of horizontal?": "VERTICAL",
  "What is the capital of Paraguay?": "ASUNCION",
  "What do you call a group of wildcats?": "DESTRUCTION",
  "What is the largest prehistoric reptile?": "DINOSAUR",
  "What is the main ingredient in burgers?": "BEEF",
  "What do you call a baby snail?": "LARVAE",
  "What is the opposite of digital?": "ANALOG",
  "What is the capital of Bolivia?": "SUCRE",
  "What do you call a group of ocelots?": "CLUTTER",
  "What is the largest living reptile?": "CROCODILE",
  "What is the main ingredient in tacos?": "CORN",
  "What do you call a baby slug?": "LARVAE",
  "What is the opposite of mechanical?": "MANUAL",
  "What is the capital of Guyana?": "GEORGETOWN",
  "What do you call a group of servals?": "CLUSTER",
  "What is the largest living bird?": "OSTRICH",
  "What is the main ingredient in sushi?": "RICE",
  "What do you call a baby worm?": "LARVAE",
  "What is the opposite of electric?": "MANUAL",
  "What is the capital of Suriname?": "PARAMARIBO",
  "What do you call a group of caracals?": "CLUTTER",
  "What is the largest living fish?": "WHALE",
  "What is the main ingredient in bread rolls?": "FLOUR",
  "What do you call a baby butterfly?": "CATERPILLAR",
});
