"""Per-environment bucket + public-domain config for avatars.

Avatars live in a dedicated bucket per env (``clawbits-avatars-{env}``)
so they're cleanly separated from legacy share-records and chat
attachments. The bucket and the public domain that fronts it are read
from env vars at call time so test setups can override them without
restarting the process.

If ``CLAWBITS_AVATARS_BUCKET`` or ``CLAWBITS_AVATARS_DOMAIN`` aren't
set, we fall back to the legacy ``CLOUDFLARE_BUCKET`` / ``SHARE_DOMAIN``
values — this keeps the module functional in any env that hasn't
adopted the new vars yet, at the cost of avatars sharing storage with
share-records.

``CURRENT_AVATAR_VERSION`` lives here so both the backfill (bumps
legacy rows up to this) and the row-creation code (starts new rows at
this) agree on the latest visual identity. Bump it whenever the
generator's output should be considered a different image — style
swap, palette change, anything that should invalidate browser caches.
"""
from __future__ import annotations

import os

from clawbits.cloudflare.r2_s3_client import R2S3Client
from clawbits.domain import SHARE_DOMAIN

# Version 9: avatars are now generated by the self-hosted DiceBear sidecar
# (DICEBEAR_BASE) on the current DiceBear v10 styles, instead of the public
# v9 API. The bump gives every entity a fresh versioned URL so the CDN/browser
# caches miss and serve the new render (overwriting the old v8 key in place
# would keep the immutable-cached v9 art). Backfill regenerates all rows.
CURRENT_AVATAR_VERSION = 9


def avatars_bucket() -> str:
    """Bucket name avatars live in. Read at call time, not at import."""
    return os.getenv("CLAWBITS_AVATARS_BUCKET") or os.getenv(
        "CLOUDFLARE_BUCKET", "clawbits-clawbits-storage"
    )


def avatars_domain() -> str:
    """Public domain that fronts the avatars bucket. Read at call time."""
    return os.getenv("CLAWBITS_AVATARS_DOMAIN") or SHARE_DOMAIN


def make_avatars_r2_client() -> R2S3Client:
    """Build an :class:`R2S3Client` wired to the avatars bucket.

    Uses the S3 API (R2 access keys) rather than the Cloudflare REST token —
    see :mod:`clawbits.cloudflare.r2_s3_client`. Passes an explicit bucket +
    public domain so the legacy share-records client (which defaults to
    ``CLOUDFLARE_BUCKET`` / ``SHARE_DOMAIN``) is unaffected.
    """
    return R2S3Client(
        bucket=avatars_bucket(),
        custom_domain=avatars_domain(),
    )
