#!/usr/bin/env python3
"""Generate src/known_answers.rs from the Clawbits known-answers table.

The Clawbits agentic write-auth "challenge" is a deterministic dictionary
lookup: the server samples a (question, answer) pair from a fixed pool and
validates the answer. This channel embeds the same table so it can solve the
challenge offline (no LLM required), mirroring the OpenClaw plugin's bundled
`knownAnswers.ts`.

Source of truth: clawbits/datastructures/known_answers.py (this repo). If the
server rotates the question pool, re-run this generator and rebuild the channel.

Usage:
    python3 gen_known_answers.py [path/to/known_answers.py]

Defaults to ../clawbits/datastructures/known_answers.py relative to this script
(this package lives beside the Clawbits server package in the Clawbits repo).
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
# Sibling of this package in the Clawbits repo: ../clawbits/datastructures/...
DEFAULT_SRC = HERE / ".." / "clawbits" / "datastructures" / "known_answers.py"
OUT = HERE / "src" / "known_answers.rs"


def load_pairs(src: Path) -> list[tuple[str, str]]:
    tree = ast.parse(src.read_text(encoding="utf-8"), filename=str(src))
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "KNOWN_QUESTIONS_ANSWERS":
                    raw = ast.literal_eval(node.value)
                    return [(str(q), str(a)) for q, a in raw]
    raise SystemExit(f"KNOWN_QUESTIONS_ANSWERS not found in {src}")


def main() -> None:
    src = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else DEFAULT_SRC.resolve()
    if not src.exists():
        raise SystemExit(
            f"Source not found: {src}\n"
            "Pass the path to clawbits/datastructures/known_answers.py explicitly."
        )

    pairs = load_pairs(src)

    # First-match wins, matching the Python get_answer_for_question semantics.
    seen: dict[str, str] = {}
    for q, a in pairs:
        seen.setdefault(q, a)

    lines = [
        "// @generated by gen_known_answers.py from",
        "// clawbits/datastructures/known_answers.py — do not edit by hand.",
        "//",
        "// The Clawbits write-auth challenge is a deterministic dictionary lookup.",
        "// Re-run `python3 gen_known_answers.py` and rebuild if the server rotates",
        "// its question pool.",
        "",
        "/// Look up the canonical answer for a challenge question.",
        "///",
        "/// Returns `None` when the question is not in the bundled table; the caller",
        "/// retries with a fresh challenge until it draws a known question.",
        "pub fn answer_for(question: &str) -> Option<&'static str> {",
        "    match question {",
    ]
    for q, a in seen.items():
        lines.append(f"        {rust_str(q)} => Some({rust_str(a)}),")
    lines.extend(
        [
            "        _ => None,",
            "    }",
            "}",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::answer_for;",
            "",
            "    #[test]",
            "    fn known_question_resolves() {",
            '        assert_eq!(answer_for("What is the capital of France?"), Some("PARIS"));',
            "    }",
            "",
            "    #[test]",
            "    fn unknown_question_is_none() {",
            '        assert_eq!(answer_for("What is my bot token?"), None);',
            "    }",
            "}",
            "",
        ]
    )

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(seen)} entries from {src})")


def rust_str(s: str) -> str:
    """Render a Python string as a Rust string literal."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


if __name__ == "__main__":
    main()
